# .github/workflows/daily_check_final.yml
name: 📊 Daily Check (WORKING)

on:
  workflow_dispatch:  # 수동 실행으로 테스트
    
jobs:
  check-daily-progress:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 체크아웃
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: 🐍 Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 🔧 Git 설정
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: 🔍 환경 확인
      run: |
        echo "📂 현재 디렉토리: $(pwd)"
        echo "📁 파일 목록:"
        ls -la
        echo "📄 README 파일들:"
        find . -name "README.md"
        echo "📁 8월3주차 내용:"
        ls -la "8월3주차/"
        
    - name: 📊 일일 진행상황 체크
      run: |
        echo "🚀 일일 알고리즘 스터디 체크 시작!"
        python scripts/daily_check.py
        
    - name: 📈 진행률 업데이트 (수정된 버전)
      run: |
        echo "📈 진행률 업데이트 시작!"
        python scripts/update_progress.py
        
    - name: 🔍 실행 후 확인
      run: |
        echo "🔍 실행 후 상태 확인"
        git status
        echo ""
        echo "📊 생성된 로그:"
        ls -la logs/
        
    - name: 💾 커밋 및 푸시
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "📝 변경사항 발견"
          git add .
          git commit -m "📊 자동 업데이트: $(date +'%Y-%m-%d %H:%M') - 경로 수정 버전"
          git push origin master
          echo "✅ 푸시 완료!"
        else
          echo "ℹ️  변경사항 없음"
        fi