# .github/workflows/debug_check.yml
name: 🔍 Debug Check

on:
  workflow_dispatch:
    
jobs:
  debug-environment:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 체크아웃
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: 🔍 환경 정보 확인
      run: |
        echo "🔍 GitHub Actions 환경 디버깅"
        echo "================================"
        echo "📂 현재 작업 디렉토리: $(pwd)"
        echo "📂 디렉토리 내용:"
        ls -la
        
    - name: 🔍 파일 구조 확인
      run: |
        echo "📁 전체 파일 구조:"
        find . -type f | head -20
        echo ""
        echo "📄 README.md 파일들 찾기:"
        find . -name "README.md" -type f
        
    - name: 🔍 8월3주차 폴더 확인
      run: |
        echo "📁 8월3주차 폴더 확인:"
        if [ -d "8월3주차" ]; then
          echo "✅ 8월3주차 폴더 존재"
          ls -la "8월3주차/"
          if [ -f "8월3주차/README.md" ]; then
            echo "✅ 8월3주차/README.md 존재"
            echo "파일 크기: $(stat -c%s "8월3주차/README.md") bytes"
          else
            echo "❌ 8월3주차/README.md 없음"
          fi
        else
          echo "❌ 8월3주차 폴더 없음"
        fi
        
    - name: 🧪 폴더 생성 테스트
      run: |
        echo "🧪 폴더 생성 테스트"
        mkdir -p "8월3주차/0820"
        echo "test file" > "8월3주차/test.txt"
        echo "✅ 테스트 파일 생성 완료"
        ls -la "8월3주차/"
        
    - name: 🔍 Git 상태 확인
      run: |
        echo "🔍 Git 상태:"
        git status
        echo ""
        echo "📊 최근 커밋:"
        git log --oneline -3